services:
  api:
    image: markdown-note-fastapi

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - markdown-note-venv:/app/.venv

    command: >
      sh -c "uv sync && uv run --no-sync uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  test:
    image: markdown-note-fastapi

    env_file:
      - .env.test

    volumes:
      - .:/app
      - markdown-note-venv:/app/.venv

    entrypoint: >
      sh -c "uv sync && uv run --no-sync pytest \"$@\"" --

  db:
    image: postgres:16

    env_file:
      - .env.db

    volumes:
      - markdown-note-dev:/var/lib/postgresql/data

  test-db:
    image: postgres:16

    env_file:
      - .env.test-db

    volumes:
      - markdown-note-test:/var/lib/postgresql/data

volumes:
  markdown-note-venv:
  markdown-note-dev:
  markdown-note-test:
