"""revise minimum models

Revision ID: 7e92293fb0b9
Revises: 93142b095075
Create Date: 2026-05-31 14:51:50.942921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e92293fb0b9'
down_revision: Union[str, Sequence[str], None] = '93142b095075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('follows')
    op.create_unique_constraint('uq_article_tags_article_id_tag_id', 'article_tags', ['article_id', 'tag_id'])
    op.drop_constraint(op.f('comments_parent_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('comments_parent_id_fkey'), 'comments', 'comments', ['parent_id'], ['id'])
    op.drop_constraint('uq_article_tags_article_id_tag_id', 'article_tags', type_='unique')
    op.create_table('follows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint('actor_id <> target_id', name=op.f('no_self_follow')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('follows_actor_id_fkey')),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('follows_target_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('follows_pkey')),
    sa.UniqueConstraint('actor_id', 'target_id', name=op.f('uq_actor_id_target_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('FOLLOW', 'LIKE', 'COMMENT', 'REPLY', name='event_type'), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('notifications_actor_id_fkey')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('notifications_article_id_fkey')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('notifications_comment_id_fkey')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('notifications_receiver_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
